services:
  web:
    build:
      context: .
    restart: always
    networks:
      - shopping
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/share/nginx/html

volumes:
  web:
networks:
  shopping:
    external: true
    name: shopping
    